version: '3.8'
services:
  db:
    image: postgres:16-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: playnext_db
      POSTGRES_USER: kevinhoffmann
      # This pulls the password from the .env file in the same directory as docker-compose.yml
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
  app:
    build: .
    ports:
      - "8000:8000"
    # This ./.env tells the 'app' service to load its environment variables from the .env file
    # located in the root of its build context (your project root).
    # If DATABASE_URL is defined in that .env, it will be used.
    env_file:
      - ./.env
    depends_on:
      - db
    environment:
      # If your app's .env file (the one loaded by env_file) doesn't have DATABASE_URL,
      # you can define it here, pulling the password from the docker-compose .env file.
      # However, it's generally cleaner to define DATABASE_URL in the app's .env.
      # Assuming DATABASE_URL will be in your app's .env or it will be derived from PG environment vars.
      # If not, you can define it like this:
      DATABASE_URL: postgresql://kevinhoffmann:${POSTGRES_PASSWORD}@db:5432/playnext_db
volumes:
  pgdata: