"""Add image_url and age_rating to Game model

Revision ID: 275087fbf429
Revises: db9c4386ee81
Create Date: 2025-03-24 16:01:27.183899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '275087fbf429'
down_revision: Union[str, None] = 'db9c4386ee81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('age_rating', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_games_game_name'), 'games', ['game_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_games_game_name'), table_name='games')
    op.drop_column('games', 'age_rating')
    # ### end Alembic commands ###
