"""create all initial tables and schema

Revision ID: abcb188f02de
Revises: 
Create Date: 2025-05-23 14:35:36.618141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abcb188f02de'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('game_name', sa.String(), nullable=True),
    sa.Column('genre', sa.String(), nullable=True),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('platform', sa.String(), nullable=True),
    sa.Column('igdb_id', sa.Integer(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('age_rating', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('game_id')
    )
    op.create_index(op.f('ix_games_game_id'), 'games', ['game_id'], unique=False)
    op.create_index(op.f('ix_games_game_name'), 'games', ['game_name'], unique=False)
    op.create_index(op.f('ix_games_igdb_id'), 'games', ['igdb_id'], unique=True)
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('registration_date', sa.DateTime(), nullable=True),
    sa.Column('user_age', sa.Integer(), nullable=True),
    sa.Column('igdb_id', sa.Integer(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('backlog_items',
    sa.Column('backlog_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('playing', 'completed', 'dropped', name='backlogstatus'), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.game_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('backlog_id')
    )
    op.create_index(op.f('ix_backlog_items_backlog_id'), 'backlog_items', ['backlog_id'], unique=False)
    op.create_table('ratings',
    sa.Column('rating_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('rating_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.game_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('rating_id')
    )
    op.create_index(op.f('ix_ratings_rating_id'), 'ratings', ['rating_id'], unique=False)
    op.create_table('recommendations',
    sa.Column('recommendation_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('recommendation_reason', sa.String(), nullable=True),
    sa.Column('documentation_rating', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.game_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('recommendation_id')
    )
    op.create_index(op.f('ix_recommendations_recommendation_id'), 'recommendations', ['recommendation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recommendations_recommendation_id'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_ratings_rating_id'), table_name='ratings')
    op.drop_table('ratings')
    op.drop_index(op.f('ix_backlog_items_backlog_id'), table_name='backlog_items')
    op.drop_table('backlog_items')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_games_igdb_id'), table_name='games')
    op.drop_index(op.f('ix_games_game_name'), table_name='games')
    op.drop_index(op.f('ix_games_game_id'), table_name='games')
    op.drop_table('games')
    # ### end Alembic commands ###
